name: checkstyle
on: push
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dbelyaev/action-checkstyle@v0.7.4
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
